plugins {
    id 'com.android.application'
    id 'org.jlleitschuh.gradle.ktlint'
}

ktlint {
    version = '1.8.0'
    android = true
    ignoreFailures = false
    reporters {
        reporter 'plain'
        reporter 'html'
    }
    filter {
        exclude { it.file.path.contains('/build/') }
    }
}

android {
    namespace 'com.example.adarsh.rajamantrichorsipahi'
    compileSdk 36

    defaultConfig {
        applicationId "com.chit.adarsh.rajamantrichorsipahi"
        minSdk 23
        targetSdk 36
        versionCode 12
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.google.android.gms:play-services-ads:24.5.0'
}
